version: "3.5"

services:

  db-server:
    image: postgres:14-alpine
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
    volumes:
      - db-server-vol:/var/lib/postgresql/data

  auth-server:
    image: jboss/keycloak:16.1.1
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    ports:
    - "8080:8080"
    volumes:
      - auth-server-vol:/opt/jboss/keycloak/standalone/data

  discovery-server:
    image: ngineapps/concierge-discovery-service:0.0.1-20220611-162529
    ports:
    - "8018:8018"

  gateway-server:
    image: ngineapps/concierge-api-gateway:0.0.1-20220611-162529
    environment:
    - DEFAULT_ZONE=http://discovery-server:8018/eureka/
    ports:
    - "8008:8008"
    depends_on:
    - discovery-server

  debit-accounts:
    image: ngineapps/concierge-debit-accounts:0.0.1-20220611-162529
    environment:
    - DEBIT_ACCOUNTS_DB_USER=postgres
    - DEBIT_ACCOUNTS_DB_PASSWORD=postgres
    - DEBIT_ACCOUNTS_DB_NAME=postgres
    - DEBIT_ACCOUNTS_DB_READ_WRITE_HOST=db-server
    - DEBIT_ACCOUNTS_DB_READ_WRITE_PORT=5432
    - DEBIT_ACCOUNTS_DB_READ_ONLY_HOST=db-server
    - DEBIT_ACCOUNTS_DB_READ_ONLY_PORT=5432
    - DISCOVERY_ENDPOINT=http://discovery-server:8018/eureka/
    - GATEWAY_URL=http://gateway-server:8008
    - ISSUER_URI=http://auth-server:8080/auth/realms/concierge
    depends_on:
    - auth-server
    - db-server
    - gateway-server    

  user-management:
    image: ngineapps/concierge-user-management:0.0.1-20220611-162529
    environment:
    - USER_MANAGEMENT_DB_USER=postgres
    - USER_MANAGEMENT_DB_PASSWORD=postgres
    - USER_MANAGEMENT_DB_NAME=postgres
    - USER_MANAGEMENT_DB_READ_WRITE_HOST=db-server
    - USER_MANAGEMENT_DB_READ_WRITE_PORT=5432
    - USER_MANAGEMENT_DB_READ_ONLY_HOST=db-server
    - USER_MANAGEMENT_DB_READ_ONLY_PORT=5432
    - DISCOVERY_ENDPOINT=http://discovery-server:8018/eureka/
    - GATEWAY_URL=http://gateway-server:8008
    - ISSUER_URI=http://auth-server:8080/auth/realms/concierge
    depends_on:
    - auth-server
    - db-server
    - gateway-server    

networks:
  default:
    external:
      name: concierge
      
volumes:  
    auth-server-vol:
      external: true
    db-server-vol:
      external: true      
